name: Deploy to EC2

on:
  push:
    paths:
      - 'FRONT/**'  # Monitora alterações na pasta FRONT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts


      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2Key.pem
          chmod 400 ec2Key.pem

      - name: Deploy to EC2
        run: ssh -i "ec2Key.pem" root@${{ secrets.EC2_HOST }} 'cd /home/ec2-user/Zoodex && git pull && cp -rf FRONT/src /usr/share/nginx/html/'
